# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('permissions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StateInheritanceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.Permission', verbose_name='Permission')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.State', verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='StateObjectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Content id')),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='contenttypes.ContentType', verbose_name='Content type')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.State', verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='StateObjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Content id')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_object', to='contenttypes.ContentType', verbose_name='Content type')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.State', verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='StatePermissionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.Permission', verbose_name='Permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.Role', verbose_name='Role')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.State', verbose_name='State')),
            ],
            options={
                'verbose_name': 'State Permission Relation',
                'verbose_name_plural': 'States Permissions Relations',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename')),
                ('condition', models.CharField(blank=True, max_length=100, verbose_name='Condition')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_state', to='workflows.State', verbose_name='Destination')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.Permission', verbose_name='Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename')),
                ('initial_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state', to='workflows.State')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowModelRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', unique=True, verbose_name='Content Type')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wmrs', to='workflows.Workflow', verbose_name='Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowObjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Content id')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_object', to='contenttypes.ContentType', verbose_name='Content type')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wors', to='workflows.Workflow', verbose_name='Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowPermissionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permissions.Permission')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Workflow')),
            ],
        ),
        migrations.AddField(
            model_name='workflow',
            name='permissions',
            field=models.ManyToManyField(through='workflows.WorkflowPermissionRelation', to='permissions.Permission'),
        ),
        migrations.AddField(
            model_name='transition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.Workflow', verbose_name='Workflow'),
        ),
        migrations.AddField(
            model_name='state',
            name='transitions',
            field=models.ManyToManyField(blank=True, related_name='states', to='workflows.Transition', verbose_name='Transitions'),
        ),
        migrations.AddField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflows.Workflow', verbose_name='Workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowpermissionrelation',
            unique_together=set([('workflow', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='workflowobjectrelation',
            unique_together=set([('content_type', 'content_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='workflowmodelrelation',
            unique_together=set([('workflow', 'content_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='statepermissionrelation',
            unique_together=set([('state', 'permission', 'role')]),
        ),
        migrations.AlterUniqueTogether(
            name='stateobjectrelation',
            unique_together=set([('content_type', 'content_id', 'state')]),
        ),
    ]
